#ifndef GRACEFUL_BL_OFFSETS_HEADER
#define GRACEFUL_BL_OFFSETS_HEADER

#define GRACEFUL_BL_DECOMPRESSOR_I386_PC_COMPRESSED_SIZE	    0x08

#define GRACEFUL_BL_DECOMPRESSOR_I386_PC_UNCOMPRESSED_SIZE	    0x0c

/* Offset of reed_solomon_redundancy.  */
#define GRACEFUL_BL_KERNEL_I386_PC_REED_SOLOMON_REDUNDANCY	    0x10

/* Offset of field holding no reed solomon length.  */
#define GRACEFUL_BL_KERNEL_I386_PC_NO_REED_SOLOMON_LENGTH       0x14

#define GRACEFUL_BL_DECOMPRESSOR_I386_PC_BOOT_DEVICE            0x18

#define GRACEFUL_BL_DECOMPRESSOR_I386_PC_MAX_DECOMPRESSOR_SIZE  (0x9000-0x8200)

/* The segment where the kernel is loaded.  */
#define GRACEFUL_BL_BOOT_I386_PC_KERNEL_SEG		                0x800

#define GRACEFUL_BL_KERNEL_I386_PC_LINK_ADDR		            0x9000
#define GRACEFUL_BL_KERNEL_I386_XEN_PVH_LINK_ADDR	            0x100000

/* The upper memory area (starting at 640 kiB).  */
#define GRACEFUL_BL_MEMORY_I386_PC_UPPER		                0xa0000
#define GRACEFUL_BL_MEMORY_I386_QEMU_UPPER		                GRACEFUL_BL_MEMORY_I386_PC_UPPER

#define GRACEFUL_BL_BOOT_I386_QEMU_CORE_ENTRY_ADDR	            0x4

#define GRACEFUL_BL_KERNEL_I386_QEMU_CORE_ENTRY_ADDR	        0x8

#define GRACEFUL_BL_KERNEL_I386_QEMU_LINK_ADDR                  0x9000

#define GRACEFUL_BL_KERNEL_SPARC64_IEEE1275_TOTAL_MODULE_SIZE	0x8
#define GRACEFUL_BL_KERNEL_ARM_STACK_SIZE                       0x40000

#define GRACEFUL_BL_BOOT_SPARC64_IEEE1275_LIST_SIZE	            12

#define GRACEFUL_BL_BOOT_SPARC64_IEEE1275_IMAGE_ADDRESS	        0x4400
#define GRACEFUL_BL_KERNEL_SPARC64_IEEE1275_LINK_ADDR           0x4400

#define GRACEFUL_BL_KERNEL_POWERPC_IEEE1275_LINK_ALIGN          4
#define GRACEFUL_BL_KERNEL_POWERPC_IEEE1275_LINK_ADDR           0x200000

#define GRACEFUL_BL_KERNEL_MIPS_LOONGSON_LINK_ADDR              0x80200000

#define GRACEFUL_BL_KERNEL_MIPS_LOONGSON_LINK_ALIGN                     32

#define GRACEFUL_BL_DECOMPRESSOR_MIPS_LOONGSON_COMPRESSED_SIZE          0x8
#define GRACEFUL_BL_DECOMPRESSOR_MIPS_LOONGSON_UNCOMPRESSED_SIZE        0xc
#define GRACEFUL_BL_DECOMPRESSOR_MIPS_LOONGSON_UNCOMPRESSED_ADDR        0x10

#define GRACEFUL_BL_KERNEL_MIPS_LOONGSON_TOTAL_MODULE_SIZE	            0x08

#define GRACEFUL_BL_KERNEL_MIPS_QEMU_MIPS_LINK_ADDR                     0x80200000
#define GRACEFUL_BL_KERNEL_MIPS_QEMU_MIPS_LINK_ALIGN                    32
#define GRACEFUL_BL_DECOMPRESSOR_MIPS_QEMU_MIPS_COMPRESSED_SIZE         0x8
#define GRACEFUL_BL_DECOMPRESSOR_MIPS_QEMU_MIPS_UNCOMPRESSED_SIZE       0xc
#define GRACEFUL_BL_DECOMPRESSOR_MIPS_QEMU_MIPS_UNCOMPRESSED_ADDR       0x10
#define GRACEFUL_BL_KERNEL_MIPS_QEMU_MIPS_TOTAL_MODULE_SIZE	            0x08

#define GRACEFUL_BL_KERNEL_MIPS_ARC_LINK_ADDR                           0x88200000
#define GRACEFUL_BL_KERNEL_MIPSEL_ARC_LINK_ADDR                         0x80700000
#define GRACEFUL_BL_KERNEL_MIPS_ARC_LINK_ALIGN                          32

#define GRACEFUL_BL_DECOMPRESSOR_MIPS_ARC_COMPRESSED_SIZE               0x8
#define GRACEFUL_BL_DECOMPRESSOR_MIPS_ARC_UNCOMPRESSED_SIZE             0xc
#define GRACEFUL_BL_DECOMPRESSOR_MIPS_ARC_UNCOMPRESSED_ADDR             0x10

#define GRACEFUL_BL_KERNEL_MIPS_ARC_TOTAL_MODULE_SIZE	                0x08

#define GRACEFUL_BL_KERNEL_I386_COREBOOT_LINK_ADDR	                    0x9000
#define GRACEFUL_BL_KERNEL_I386_COREBOOT_MODULES_ADDR                   0x100000

#define GRACEFUL_BL_KERNEL_I386_IEEE1275_LINK_ADDR	                    0x10000

#define GRACEFUL_BL_KERNEL_I386_IEEE1275_MOD_ALIGN	                    0x1000
#define GRACEFUL_BL_KERNEL_I386_COREBOOT_MOD_ALIGN	                    0x1
#define GRACEFUL_BL_KERNEL_I386_MULTIBOOT_MOD_ALIGN	                    GRACEFUL_BL_KERNEL_I386_COREBOOT_MOD_ALIGN

#define GRACEFUL_BL_KERNEL_X86_64_XEN_MOD_ALIGN	                        0x8
#define GRACEFUL_BL_KERNEL_I386_XEN_MOD_ALIGN		                    0x8
#define GRACEFUL_BL_KERNEL_I386_XEN_PVH_MOD_ALIGN	                    0x8

/* Non-zero value is only needed for PowerMacs.  */
#define GRACEFUL_BL_KERNEL_X86_64_XEN_MOD_GAP		                    0x0
#define GRACEFUL_BL_KERNEL_I386_XEN_MOD_GAP		                        0x0
#define GRACEFUL_BL_KERNEL_I386_XEN_PVH_MOD_GAP	                        0x0
#define GRACEFUL_BL_KERNEL_I386_IEEE1275_MOD_GAP	                    0x0
#define GRACEFUL_BL_KERNEL_I386_COREBOOT_MOD_GAP	                    0x0
#define GRACEFUL_BL_KERNEL_SPARC64_IEEE1275_MOD_GAP	                    0x0
#define GRACEFUL_BL_KERNEL_ARM_UBOOT_MOD_GAP		                    0x0

#define GRACEFUL_BL_KERNEL_POWERPC_IEEE1275_MOD_ALIGN                   0x1000
#define GRACEFUL_BL_KERNEL_SPARC64_IEEE1275_LOG_MOD_ALIGN               3
#define GRACEFUL_BL_KERNEL_SPARC64_IEEE1275_MOD_ALIGN                   (1 << GRACEFUL_BL_KERNEL_SPARC64_IEEE1275_LOG_MOD_ALIGN)

#define GRACEFUL_BL_KERNEL_MIPS_LOONGSON_MOD_ALIGN                      0x1
#define GRACEFUL_BL_KERNEL_MIPS_ARC_MOD_ALIGN                           0x1
#define GRACEFUL_BL_KERNEL_MIPS_QEMU_MIPS_MOD_ALIGN                     0x1

#define GRACEFUL_BL_KERNEL_ARM_UBOOT_MOD_ALIGN 	                        0x8
#define GRACEFUL_BL_KERNEL_ARM_UBOOT_TOTAL_MODULE_SIZE	                0x4

#define GRACEFUL_BL_KERNEL_ARM_COREBOOT_MOD_ALIGN 	                    0x8
#define GRACEFUL_BL_KERNEL_ARM_COREBOOT_TOTAL_MODULE_SIZE	            0x4

#define GRACEFUL_BL_KERNEL_ARM_STACK_SIZE                               0x40000
#define GRACEFUL_BL_KERNEL_ARM_COREBOOT_MOD_GAP                         (GRACEFUL_BL_KERNEL_ARM_STACK_SIZE + 1024)

#define GRACEFUL_BL_KERNEL_POWERPC_IEEE1275_MOD_GAP 0x8000

#ifdef  GRACEFUL_BL_MACHINE

#define GRACEFUL_BL_OFFSETS_CONCAT_(a,b,c) a##b##c
#define GRACEFUL_BL_OFFSETS_CONCAT(a,b,c) GRACEFUL_BL_OFFSETS_CONCAT_(a,b,c)
#define GRACEFUL_BL_KERNEL_MACHINE_MOD_ALIGN    GRACEFUL_BL_OFFSETS_CONCAT(GRACEFUL_BL_KERNEL_,GRACEFUL_BL_MACHINE,_MOD_ALIGN)
#define GRACEFUL_BL_KERNEL_MACHINE_MOD_GAP      GRACEFUL_BL_OFFSETS_CONCAT(GRACEFUL_BL_KERNEL_,GRACEFUL_BL_MACHINE,_MOD_GAP)
#define GRACEFUL_BL_KERNEL_MACHINE_TOTAL_MODULE_SIZE GRACEFUL_BL_OFFSETS_CONCAT(GRACEFUL_BL_KERNEL_,GRACEFUL_BL_MACHINE,_TOTAL_MODULE_SIZE)

#define GRACEFUL_BL_BOOT_MACHINE_KERNEL_SEG GRACEFUL_BL_OFFSETS_CONCAT (GRACEFUL_BL_BOOT_, GRACEFUL_BL_MACHINE, _KERNEL_SEG)

#define GRACEFUL_BL_MEMORY_MACHINE_UPPER GRACEFUL_BL_OFFSETS_CONCAT(GRACEFUL_BL_MEMORY_,GRACEFUL_BL_MACHINE,_UPPER)
#if defined(GRACEFUL_BL_MACHINE_ARC) && defined(GRACEFUL_BL_CPU_MIPSEL)
#define GRACEFUL_BL_MACHINE_LINK_ADDR GRACEFUL_BL_KERNEL_MIPSEL_ARC_LINK_ADDR
#else
#define GRACEFUL_BL_MACHINE_LINK_ADDR GRACEFUL_BL_OFFSETS_CONCAT(GRACEFUL_BL_KERNEL_,GRACEFUL_BL_MACHINE,_LINK_ADDR)
#endif

#define GRACEFUL_BL_DECOMPRESSOR_MACHINE_COMPRESSED_SIZE    GRACEFUL_BL_OFFSETS_CONCAT(GRACEFUL_BL_DECOMPRESSOR_,GRACEFUL_BL_MACHINE,_COMPRESSED_SIZE)
#define GRACEFUL_BL_DECOMPRESSOR_MACHINE_UNCOMPRESSED_SIZE  GRACEFUL_BL_OFFSETS_CONCAT(GRACEFUL_BL_DECOMPRESSOR_,GRACEFUL_BL_MACHINE,_UNCOMPRESSED_SIZE)
#define GRACEFUL_BL_DECOMPRESSOR_MACHINE_UNCOMPRESSED_ADDR  GRACEFUL_BL_OFFSETS_CONCAT(GRACEFUL_BL_DECOMPRESSOR_,GRACEFUL_BL_MACHINE,_UNCOMPRESSED_ADDR)
#endif


#endif
